Jdbc analyzers extend histogram
hpi-bp1819-naumann/deequ pull request #53
Opened 2018-11-21 11:47 UTC by janwestphal306

*Issue #52*

*Description of changes:*
Use a binning function when the `resultSet` is evaluated.
Add a function that returns the top `n` key-value pairs of a map with respect to the value without sorting of the pairs.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2018-11-28 12:20 UTC, velramiir requested changes

2018-11-28 12:20 UTC, velramiir commented on src/main/scala/com/amazon/deequ/analyzers/jdbc/JdbcHistogram.scala
> +    PARAM_CHECK :: hasTable() :: hasColumn(column) :: Nil
I'd suggest to stick to the precondition naming pattern here. All caps is usually used for constants, not for functions. Maybe name it "hasValidParams" or "hasValidMaxDetailParam"

2018-11-28 12:35 UTC, velramiir commented on src/main/scala/com/amazon/deequ/analyzers/jdbc/JdbcHistogram.scala
> +    PARAM_CHECK :: hasTable() :: hasColumn(column) :: Nil
So, Amazon did this, too. They named it PARAM_CHECKS so just add an 's'

2018-11-28 12:36 UTC, velramiir submitted a review, later dismissed

2018-11-28 12:36 UTC, velramiir commented on src/main/scala/com/amazon/deequ/analyzers/jdbc/JdbcHistogram.scala
> +    PARAM_CHECK :: hasTable() :: hasColumn(column) :: Nil
```suggestion
    PARAM_CHECKS :: hasTable() :: hasColumn(column) :: Nil
```

2018-11-28 12:37 UTC, velramiir commented on src/main/scala/com/amazon/deequ/analyzers/jdbc/JdbcHistogram.scala
> +    PARAM_CHECK :: hasTable() :: hasColumn(column) :: Nil
```suggestion
    PARAM_CHECKS :: hasTable() :: hasColumn(column) :: Nil
```

2018-11-28 12:37 UTC, velramiir commented on src/main/scala/com/amazon/deequ/analyzers/jdbc/JdbcHistogram.scala
> +  private[this] val PARAM_CHECK: Table => Unit = { _ =>
```suggestion
  private[this] val PARAM_CHECKS: Table => Unit = { _ =>
```

2018-12-10 10:14 UTC, mschroederi approved these changes

2018-12-10 10:15 UTC, merged